version: "3.7"
services:
  envoy:
    image: envoyproxy/envoy:v1.26.4-lua-basic-auth
    build: .
    hostname: envoy
    ports:
      - "10000:10000"
    environment:
      - GODEBUG=cgocheck=0
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./basic-auth.lua:/etc/envoy/basic-auth.lua
    healthcheck:
      test: [ "CMD", "curl", "-f", "-H", "Authorization: Basic ZGVuZ3d1Lndhbmc6cGFzc3dvcmQ=", "http://localhost:10000/" ]
      interval: 1s
    networks:
      - envoymesh
    depends_on:
      nginx:
        condition:
          service_healthy
  nginx:
    image: nginx
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:10001/" ]
      interval: 1s
    networks:
      - envoymesh
  fortio:
    image: fortio/fortio
    hostname: fortio
    volumes:
      - ./:/var/lib/fortio
    command: 'load -t 30s -c 10 -qps 0 -H "Authorization: Basic ZGVuZ3d1Lndhbmc6cGFzc3dvcmQ=" -labels "lua-basic-auth" -a http://envoy:10000/'
    depends_on:
      envoy:
        condition:
          service_healthy
    networks:
      - envoymesh

networks:
  envoymesh: { }
